services:
  postgres:
    image: postgres:16
    container_name: CoLevelUp
    environment:
      POSTGRES_USER: level
      POSTGRES_PASSWORD: levelpass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U level -d postgres"]

      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
